### ISSUE TITLE
Drupal package does not handle passwords correctly for some versions

### ISSUE THREAD

**Issue by DaazKu** [vanilla/porter#114]
The correct method to use should be Drupal and not Django.

**Comment by linc** [comment]
Only has of Drupal 7 or 8, I suspect.

**Comment by DaazKu** [comment]
I actually did a Drupal 6 migration and the password do not work right now. Using the Drupal HashMethod and removing the "md5$$" string that was prefixed during the importation makes everything work.

**Comment by linc** [comment]
Oh, weird. Maybe it's the reverse, then?

**Comment by DaazKu** [comment]
Maybe. 

All I know is that if these kind of password are detected:
```
U$S$9eOHZXKSNo.sDUgpkiGnn9tpbm.NYf5E5Ze3XIDTPUGPgff8YS49
$S$C.0Uzy11EZmhaYIuwMe.DniU2Yj1Od/MexlpBG/vbF9hI5hzYpZs
```
The HashMethod must be Drupal.

**Comment by DaazKu** [comment]
This ain't ever gonna be fixed
![image](https://github.com/vanilla/porter/assets/2412909/2f1a9671-4551-4f73-972f-76c40c9100d9)
