### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dusty459** [vanilla/porter#121]
Right I have converted the mybb database I got the gz file iv gone to the importer imported it 

I get Data file directory (/*****/****/public_html/vanilla/uploads/import/import) is not writable in red at top but its still running the import as I get process import file then  loading bar there is a lot of data from old forum 
and I no its takes time  but is this correct?

**Comment by DaazKu** [comment]
The importation process is part of vanilla not the porter.
I'm gonna move the issue there.

Also, please try to use a signifiant title when you create an issue. That way, other people with the same problem may find there answer using the search feature.
