### ISSUE TITLE
vBulletin blobs export (images) may crash

### ISSUE THREAD

**Issue by topcheese13** [vanilla/porter#136]
Error message:
`Error in functions/core-functions.php line 131: (8) imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Corrupt JPEG data: 217 extraneous bytes before marker 0xd9`

When images are corrupted/too old GD crashes, which makes PHP crash.

There is no way to put this in a try catch, so the script crashes entirely.

We should consider switching libraries from GD to Imagick to prevent this bug.

**Comment by linc** [comment]
What's the support like for Imagick out in the wilds?

**Comment by topcheese13** [comment]
Found a way to handle this use case without changing libraries, creating a PR.
