### ISSUE TITLE
Replace mysql native functions in all packages

### ISSUE THREAD

**Issue by topcheese13** [vanilla/porter#162]
To have all packages work regardless of the php version (5.6, 7+) we need to remove all native mysql functions from packages.

from example

```
while ($row = mysql_fetch_assoc($result)) {
```

needs to be changed to

```
 if ($result->nextResultRow() !== false) {
```

You can look at the db resource interface and the 3 different db classes (mysql, mysqli, pdo) https://github.com/vanilla/porter/tree/3e360e128b20c90b959b559f6b51f3931847e2f1/database to replace the mysql native functions by the correct functions declared in the interface.

You can also refer yourself to this PR https://github.com/vanilla/porter/pull/154 as to what changed and why.

**Comment by patrickdesjardins77** [comment]
Every mysql native function were removed from packages.
