### ISSUE TITLE
vBulletin package includes deleted conversations

### ISSUE THREAD

**Issue by patches** [vanilla/porter#192]
In vBulletin, an entry is deleted from the `vb_pm`  table when a conversation is deleted. However, an entry is left in the vb_pmtext  table. We use the vb_pmtext  table to re-create the conversations during the migration.

A check will need to be made to verify that an entry is still in the `vb_pm` table, if not, then the conversation in the `UserConversation` table needs to be marked as deleted.

**Comment by vincentlam92** [comment]
As we discuss, I think we will need to do more investigation about how VB's PM work. Since we didn't get any complaint before. We will need to be sure that will it be how VB works or it just something just for MSE.
