### ISSUE TITLE
Add to UI: Avatars, attachments, and file path options

### ISSUE THREAD

**Issue by linc** [vanilla/porter#30]
Blob exporting (avatars & attachments) should be added to vBulletin web interface.

~~Optional file path for attachment renaming should be added to vBulletin & phpBB interfaces.~~ -> #84

**Comment by tburry** [comment]
Is this really appropriate for the web interface?

**Comment by linc** [comment]
Folks who can't use the command line tools aren't allowed to have their avatars?

**Comment by Daazku** [comment]
I created a separate issue for the attachment renaming. See #84
