### ISSUE TITLE
esoTalk

### ISSUE THREAD

**Issue by alexcroox** [vanilla/porter#47]
Has anyone managed an [esoTalk](http://esotalk.org/) migration before? The developer has moved onto a new project and I'm looking to Vanilla as a platform with a future.

**Comment by linc** [comment]
I don't believe we have. There are tips for rolling your own porter in the README, but if you send me your database dump I might be able to make a quick-and-dirty one.

**Comment by alexcroox** [comment]
Oh really? That would be incredible thank you! http://cl.ly/Zmy2/d

**Comment by alexcroox** [comment]
Updated the link above as it converted blob to hex on export sorry.

**Comment by linc** [comment]
Sweet, can you create a user with password 'Testing' (no quotes) and send me what the 'password' value is for that user then? I'm gonna need a way of seeing if I got the password conversion correct. I'll give it the ol' college try, anyway.

**Comment by alexcroox** [comment]
Sure it's $2a$08$xuka.SN/bTkfmBqc0VpLZeAPR25pqyD/vY6xqy.qiOIVUn8aRlm82

**Comment by alexcroox** [comment]
It's not the end of the world if I have to force password resets when it's live though :)

**Comment by linc** [comment]
Oh fantastic, using a standard hash.

**Comment by linc** [comment]
Give it a shot: http://vanillaforums.org/addon/porter-core-2.1.5

Caveats: Does not keep private conversations (would've doubled the time investment), attachments (you don't appear to have any), or permissions (way faster for you to reset them after than to code that section). Hopefully a nice v1.

**Comment by alexcroox** [comment]
Nice thank you!!!

I get the following error when starting the import:

```There was an error while trying to create the User table (The specified data type (Confirmed) is not accepted for the MySQL database.).```

On stage 3. Define Tables

**Comment by alexcroox** [comment]
Looks like on line 3873 in $User_Map 'confirmed' => 'Confirmed' and confirmed doesn't exist in Vanilla user table. Should it be "Verified" or similar?

**Comment by alexcroox** [comment]
OK removing that part of the array seems to let it complete the import without error.

Unfortunately it doesn't look like the replies/comments are mapped to their parent post correctly.

The thread list appears correct, however when reading a conversation the replies are from different threads

**Comment by linc** [comment]
My fault, `Confirmed` is added for the upcoming 2.2 which is what I was testing against. `Verified` would be an OK alternative I suppose.

I made a capitalization error on the discussion IDs. Fix is coming.

**Comment by linc** [comment]
Did you test any logins besides your main account you imported with?

**Comment by linc** [comment]
http://vanillaforums.org/addon/porter-core-2.1.6

**Comment by alexcroox** [comment]
Seemed to work much better thank you! The only bug I've noticed at the moment is the OP is repeated once in the comments. So you get a duplicate post at the top of the thread. The rest of the comments are fine. http://cl.ly/ZnuA/d

**Comment by linc** [comment]
Thanks for the feedback! Try once more: http://vanillaforums.org/addon/porter-core-2.1.7

**Comment by alexcroox** [comment]
That seemed to fix all issues I've spotted so far. Thank you very much for your help with this.

**Comment by alexcroox** [comment]
Oh and yes the user password work, the only problem is the imported member groups/roles don't have any permissions to view any of the imported categories so user's get an error when testing login. This is easily solved by manually setting up the category permissions inside of role groups.

**Comment by linc** [comment]
Sweet!

**Comment by fbjerggaard** [comment]
@linc I am having issues with the porter - it doesn't migrate any comments to a thread and almost all the threads title is "Blank Discussion Topic".. Any idea how this might have happened?
