### ISSUE TITLE
Unable to export phpBB3.0 branch since porter v2

### ISSUE THREAD

**Issue by Carlton2001** [vanilla/porter#54]
Error: (8) unserialize(): Error at offset 11 of 191 bytes

**Comment by linc** [comment]
`$value = @unserialize($value);` is the problem. Yay error suppression.

**Comment by dericdd** [comment]
Gotta love that '@' :)

DDD

**Comment by Carlton2001** [comment]
I have the same error if I delete this '@'.

**Comment by initvector** [comment]
@Carlton2001 Using the phpbb3 package, I was able to port over a phpBB 3.0.11 installation just now.

Can you provide any more information about the circumstances in which you're encountering this error (platform you're running the porter on, specific version of phpBB, any extensions/mods, etc)?

Would it be possible to provide a copy of your database for us to review and run some tests against?  There might be some data integrity issues with the log_data field of some rows in your log table.  If you would like to purge any user information from the copy, I don't think that would adversely affect the review.

**Comment by Carlton2001** [comment]
Well you were right.

I tried the script on another install of phpBB 3.0.12 and it worked.
I duplicate the first problematic database and trucate the log_data table, the export went well.

Thank you very much !
