### ISSUE TITLE
MyBB import doesn't process on quoted posts PID and date

### ISSUE THREAD

**Issue by dandv** [vanilla/porter#61]
In a quoted post, I see this:

> Dan Dascalescu' pid='2487' dateline='1365377895' said:

Source: https://forum.quantifiedself.com/thread-zeo-shutting-down-export-your-data?pid=2638#pid2638

Imported: http://vanilla.quantifiedselfforum.com/index.php?p=/discussion/comment/2638/#Comment_2638

**Comment by Daazku** [comment]
Vanilla is only supporting basic BBCode by default.
Installing the [NBBC Plugin](http://vanillaforums.org/get/nbbc-plugin-1.1.0) will fix the issue.
