### ISSUE TITLE
[hr] is not converted when importing from MyBB

### ISSUE THREAD

**Issue by dandv** [vanilla/porter#62]
Imported post: http://vanilla.quantifiedselfforum.com/index.php?p=/discussion/comment/2659/#Comment_2659

**Comment by initvector** [comment]
Hi @dandv 

Have you tried installing the NBBC plug-in for Vanilla?  You can find it here: http://vanillaforums.org/addon/nbbc-plugin

It does a better job of handling BBCode when migrating from some platforms.  What tags it doesn't support, it may hide instead of displaying the raw code.
