### ISSUE TITLE
Nested quotes imported incorrectly

### ISSUE THREAD

**Issue by dandv** [vanilla/porter#63]
Compare the 3rd quote block, right before the "Hi Kate" at the end:

MyBB: https://forum.quantifiedself.com/thread-zeo-shutting-down-export-your-data?pid=2659#pid2659

![image](https://cloud.githubusercontent.com/assets/33569/7085451/a918370c-df2b-11e4-9a8e-3ca1c3b6b209.png)

Vanilla: http://vanilla.quantifiedselfforum.com/index.php?p=/discussion/comment/2659/#Comment_2659 - you can see "[/quote]"

![image](https://cloud.githubusercontent.com/assets/33569/7085458/b53b2b3e-df2b-11e4-9e80-e2516acf6d0f.png)

Discourse: http://discourse.quantifiedselfforum.com/t/zeo-shutting-down-export-your-data/561/6 - it nests the quotes correctly, though it still gets the quoting line wrong (includes the PID and the date is left in seconds-since-epoch format)

![image](https://cloud.githubusercontent.com/assets/33569/7085461/bf850dee-df2b-11e4-82bc-fe10ee157ad5.png)

**Comment by Daazku** [comment]
This is not a porter issue.
I created an issue in the proper repository and cross referenced this issue in it.

Also, I would suggest to try the [NBBC plugin](http://vanillaforums.org/addon/nbbc-plugin) to see if that fixes the problem.
