### ISSUE TITLE
(private) user messages missing after SMF 1 import

### ISSUE THREAD

**Issue by swigle** [vanilla/porter#68]
I posted this issue on the vanilla forum already, and fixed it for my case, but was asked to post this issue here as well:

I ran the export import from an old SMF 1 forum to a fresh vanilla install a couple of times. 
Both times, most of the personal messages from the old forum seemed to be missing when looking in the "inbox" of a user.
Looking in the database, almost all items are "deleted = 1", which seemed weird.

I've update all to deleted = 0 to check, but even then, only a few messages are showing and nothing newer then 2008 for some strange reason. So the deleted = 1 was not wrong after all.

After some database diving i found the following:
The problem is, all messages were imported properly into the GDN_conversationMessages table. But for some messages/conversations no entry was made into the GDN_conversations table, which binds different messages together in a discussion.

I've created a query to rectify this afther the import is run. This fixes this issue for me. It neatly sets amount of messages, first message id and last message id to the right settings. 
Not all columns in the GDN_conversations table can be set, but those aren't really needed for it to work.

```SQL
INSERT INTO vanilla_beta.GDN_Conversation(
   ConversationID,
  Subject,
  Contributors,
  FirstMessageID,
  LastMessageID,
  InsertUserID,
  DateInserted,
  DateUpdated,
  CountMessages
) SELECT 
    ConversationID, 
    null, 
    ' ', 
    (SELECT MessageID FROM GDN_ConversationMessage cm2 WHERE cm.ConversationID = cm2.ConversationID ORDER BY cm2.DateInserted ASC LIMIT 1), 
    (SELECT MessageID FROM GDN_ConversationMessage cm2 WHERE cm.ConversationID = cm2.ConversationID ORDER BY cm2.DateInserted DESC LIMIT 1), 
    InsertUserID, 
    DateInserted, 
    DateInserted, 
    (SELECT COUNT(*) FROM GDN_ConversationMessage cm2 WHERE cm.ConversationID = cm2.ConversationID) 
FROM GDN_ConversationMessage cm
WHERE ConversationID NOT IN (SELECT ConversationID FROM GDN_Conversation)
GROUP BY ConversationID
```

I know running this SQL doesn't solve the root of the problem, but since my client is more interested in making the deadline and keeping their users happy, i didn't debug the export/import

**Comment by initvector** [comment]
Thanks for reporting the issue, as well as your findings!  I'll take a deeper look and see what I can turn up.

For the sake of reproducing your issue, would you be able to provide a copy of the database you experienced the issue with?

**Comment by swigle** [comment]
My client won't appriciate handing over the database, so sadly no.
The best thing i can do is export the structure, but i don't think that'll help you much (?)

**Comment by Daazku** [comment]
I tried to use the porter on version 1.0.23.
The DB structure is not handled by this package.

Afterward I used version 1.1.21.
I created some users and did some PM.
Everything got migrated properly.
