### ISSUE TITLE
SQL error importing from VBulleting

### ISSUE THREAD

**Issue by Zulan** [vanilla/porter#77]
Apparantly a `null as filethumb` missing in line 12451

    select a.attachmentid, a.filename, right(a.filename, instr(reverse(a.filename), '.')) as extension , null as hash, a.filehash, a.userid,
               'local' as StorageMethod,
               'discussion' as ForeignTable,
               t.threadid as ForeignID,
               FROM_UNIXTIME(a.dateline) as DateInserted,
               '1' as height,
               '1' as width,
               null as filethumb
            from vb_thread t
               left join vb_attachment a ON a.postid = t.firstpostid
            where a.attachmentid > 0

            union all

            select a.attachmentid, a.filename, right(a.filename, instr(reverse(a.filename), '.')) as extension , null as hash, a.filehash, a.userid,
               'local' as StorageMethod,
               'comment' as ForeignTable,
               a.postid as ForeignID,
               FROM_UNIXTIME(a.dateline) as DateInserted,
               '1' as height,
               '1' as width
            from vb_post p
               inner join vb_thread t ON p.threadid = t.threadid
               left join vb_attachment a ON a.postid = p.postid
            where p.postid <> t.firstpostid and  a.attachmentid > 0
            ;The used SELECT statements have a different number of columns

Error: (1024) The used SELECT statements have a different number of columns

**Comment by Daazku** [comment]
Fixed by #73
